tags:
  [
    {
      frame: "tag_1",
      id: 1,
      corners: [
        [-0.042,0.042,0.0],
        [0.042,0.042,0.0],
        [0.042,-0.042,0.0]
      ]
    },
    {
      frame: "tag_2",
      id: 2,
      corners: [
        [-0.042,0.042,0.0],
        [0.042,0.042,0.0],
        [0.042,-0.042,0.0]
      ]
    },
    {
      frame: "tag_3",
      id: 3,
      corners: [
        [-0.042,0.042,0.0],
        [0.042,0.042,0.0],
        [0.042,-0.042,0.0]
      ]
    },
    {
      frame: "tag_8",
      id: 0,
      corners: [
        [-0.043,0.043,0.0],
        [0.043,0.043,0.0],
        [0.043,-0.043,0.0]
      ]
    },
    {
      frame: "tag_9",
      id: 9,
      corners: [
        [-0.043,0.043,0.0],
        [0.043,0.043,0.0],
        [0.043,-0.043,0.0]
      ]
    },
    {
      frame: "tag_10",
      id: 10,
      corners: [
        [-0.043,0.043,0.0],
        [0.043,0.043,0.0],
        [0.043,-0.043,0.0]
      ]
    },
    {
      frame: "tag_7",
      id: 7,
      corners: [
        [-0.043,0.043,0.0],
        [0.043,0.043,0.0],
        [0.043,-0.043,0.0]
      ]
    }
  ]
bundles:
  [
  ]

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
