tags:
  [
    {
      frame: "tag_1",
      id: 1,
      corners: [
        [-0.042,0.042,0.0],
        [0.042,0.042,0.0],
        [0.042,-0.042,0.0]
      ]
    },
    {
      frame: "tag_2",
      id: 2,
      corners: [
        [-0.042,0.042,0.0],
        [0.042,0.042,0.0],
        [0.042,-0.042,0.0]
      ]
    },
    {
      frame: "tag_3",
      id: 3,
      corners: [
        [-0.042,0.042,0.0],
        [0.042,0.042,0.0],
        [0.042,-0.042,0.0]
      ]
    },
    {
      frame: "tag_4",
      id: 4,
      corners: [
        [-0.042,0.042,0.0],
        [0.042,0.042,0.0],
        [0.042,-0.042,0.0]
      ]
    },
    {
      frame: "tag_5",
      id: 5,
      corners: [
        [-0.042,0.042,0.0],
        [0.042,0.042,0.0],
        [0.042,-0.042,0.0]
      ]
    },
    {
      frame: "tag_6",
      id: 6,
      corners: [
        [-0.042,0.042,0.0],
        [0.042,0.042,0.0],
        [0.042,-0.042,0.0]
      ]
    },
    {
      frame: "tag_7",
      id: 7,
      corners: [
        [-0.042,0.042,0.0],
        [0.042,0.042,0.0],
        [0.042,-0.042,0.0]
      ]
    }
  ]
bundles:
  [
  ]

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
